import 'model/doctor_details.dart';

final List<FavouriteDoctor> doctors = [
  FavouriteDoctor(
    id: '1',
    name: 'Dr. Milind Chauhan',
    specialization: 'General Physician',
    qualification: 'MBBS, MD - General Medicine',
    experienceYears: 27,
    rating: 4.0,
    fee: 1000,
    availableTime: '10am - 9:30pm',
    availableDays: 'Mon and Wed',
    location: 'Vishnu Dev Nagar, Wakad',
    distanceKm: 4.0,
    availableTokens: 25,
    nextAvailable: 'Tomorrow, 10:00AM',
    isFavorite: true,
    isVerified: true,
    profileInitial: 'M',
  ),
  FavouriteDoctor(
    id: '2',
    name: 'Dr. Arjun Mehta',
    specialization: 'Orthopedic',
    qualification: 'MBBS, MD - Orthopedic',
    experienceYears: 27,
    rating: 4.0,
    fee: 1000,
    availableTime: '10am - 9:30pm',
    availableDays: 'Mon and Wed',
    location: 'Vishnu Dev Nagar, Wakad',
    distanceKm: 4.0,
    availableTokens: 25,
    nextAvailable: 'Today, 10:00AM',
    isFavorite: false,
    isVerified: true,
    profileInitial: 'A',
  ),
];
